library(dplyr)
data<-read.table("household_power_consumption.txt",sep=";",na.strings="\\?",header=TRUE)
data<-filter(data,Date=="1/2/2007"|Date=="2/2/2007")
png(filename="plot1.png")
hist(as.numeric(data$Global_active_power),col="red",main="Global Active Power",xlab="Global Active Power (kilowatts)",ylab="Frequency",breaks=12)
dev.off()
